creation variables css
WildCodeSchool/js-orleans-p2-hero-game pull request #1
Opened 2020-10-23 14:43 UTC by thomas-ode

2020-10-23 14:46 UTC, MartyLucas45 approved these changes
Ok.

2020-10-23 14:55 UTC, florentdesmarets approved these changes

2020-10-23 15:05 UTC, ldupas requested changes

2020-10-23 15:05 UTC, ldupas commented on src/Main.css
> +  --light-grey: #dcdcdc;
--medium-light (si jamais vous changez votre gris pour une autre couleur dans le futur)

2020-10-26 08:30 UTC, MartyLucas45 approved these changes

2020-10-26 11:24 UTC, ldupas approved these changes

2020-10-26 11:24 UTC, merged